name: perizinan_petugas
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  # Functional programming thingies
  fpdart: ^0.0.11
  # Value equality
  equatable: ^2.0.3
  # Networking
  dio: ^4.0.0
  # Bloc for state management
  flutter_bloc: ^7.3.1
  # Service locator
  get_it: ^7.2.0
  injectable: ^1.5.0
  # GetX for route, state & dependency management
  get: ^4.3.8
  # Like kotlin sealed class
  freezed_annotation: ^0.15.0
  # Responsive UI util
  flutter_screenutil: ^5.0.0+2
  # SVG image
  flutter_svg: ^0.23.0+1
  # Form builder helper
  flutter_form_builder: ^6.1.0+1
  # Staggered grid view
  flutter_staggered_grid_view: ^0.4.1
  # No SQL local storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # Cached network image
  cached_network_image: ^3.1.0
  # Image picker
  image_picker: ^0.8.4+2
  # Permission handler
  permission_handler: ^8.2.5
  # Localization / date / number
  intl: ^0.17.0
  # Icon bundles
  font_awesome_flutter: ^9.1.0
  # Extension collections
  dartx: ^0.7.1
  # Immutable lists, sets, maps, and multimaps
  fast_immutable_collections: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.1.4
  freezed: ^0.15.0+1
  json_serializable: ^5.0.2
  hive_generator: ^1.1.1
  # Service locator
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
